version: 'latest'
services:
    mssql:
        container_name: devops23
        hostname: devops23
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Wachtwoord1!
            - MSSQL_PID=Express
        ports:
            - '1433:1433'
        image: 'mcr.microsoft.com/mssql/server:latest'
        volumes:
            - sql_data:/var/opt/mssql
volumes:
  sql_data: